bitprj/curriculum

- Module2.2_Intermediate_Python/activities/Act1_BookKeeper/1.md
> Bookkeeper 

- Node_Week_2/js-best-practices/1.md
- Node_Week_2/js-best-practices/2.md
- Node_Week_2/js-best-practices/3.md
- Node_Week_2/js-best-practices/4.md
- Node_Week_2/js-best-practices/5.md
- Node_Week_2/js-best-practices/7.md
- Node_Week_2/js-best-practices/8.md
- Node_Week_2/js-best-practices/9.md
copied all .md files from exercises
> Copied js-best-practices files

- Node_Week_2/js-best-practices/Part 2/5.md
Edited js-best-practices Part 2 5.md #128
> Resolving Issue #128

- Module4.3_Search_and_Sorting_Algorithms/activities/Act1_SearchingAndSorting/4.md
-toned down the friendly/personal tone to make it more in line with the other cards in this section
-removed pancake photo as a result :(
Closes #55
> Resolve Issue #55  

- Module4.3_Search_and_Sorting_Algorithms/activities/Act1_SearchingAndSorting/3.md
-fixed wording of first sentence so DFS is no longer stated to be the opposite of BFS, instead provides a transition from previous section
Closes #55
> Resolve Issue #55

- Module4.3_Search_and_Sorting_Algorithms/activities/Act1_SearchingAndSorting/2.md
merging into activity/lab branches
> Brandon searching and sorting 2

- Module4.3_Search_and_Sorting_Algorithms/activities/Act1_SearchingAndSorting/1.md
merging into activity/lab branches
> Emily searchingand sorting activity

- Module4.3_Search_and_Sorting_Algorithms/activities/Act2_Sorting/4.md
merging into activity/lab branches
> Emily sorting activity

- Module4_Labs/Lab1_BFS_Maze/Cards/111.md
- Module4_Labs/Lab1_BFS_Maze/Cards/2.md
- Module4_Labs/Lab1_BFS_Maze/Cards/3.md
- Module4_Labs/Lab1_BFS_Maze/Cards/4.md
- Module4_Labs/Lab1_BFS_Maze/Cards/421.md
- Module4_Labs/Lab1_BFS_Maze/Cards/431.md
/Closes #267 
/Closes #269 
/Closes #278
> issue 267,269,278

- Module4_Labs/Lab3_File_System/Cards/1.md
- Module4_Labs/Lab3_File_System/Cards/2.md
- Module4_Labs/Lab3_File_System/Cards/421.md
- Module4_Labs/Lab3_File_System/Cards/422.md
- Module4_Labs/Lab6_Sudoku_Solver/Cards/41.md
- Module4_Labs/Lab6_Sudoku_Solver/Cards/411.md
- Module4_Labs/Lab6_Sudoku_Solver/Cards/7.md
- Module4_Labs/Lab6_Sudoku_Solver/Cards/71.md
- Module4_Labs/Lab6_Sudoku_Solver/Cards/711.md
- Module4_Labs/Lab6_Sudoku_Solver/Cards/91.md
- Module4_Labs/Lab6_Sudoku_Solver/Cards/911.md
- Module4_Labs/Lab6_Sudoku_Solver/Cards/912.md
Closes Issues #290  #293  #296 .
* Fixed issues regarding instructions descriptions, moving textfile example, resizing images, code alignment in DSA LAB 3 (was not sure about skeleton code reference, however)
* Reorganized hints given in 7.md, provided reminders for `complete()` function, renamed variable dup in various places, explained various code lines, etc. in Lab 4.6 Sudoku Solver.  
@reviewer/Sarah
> Taimur_WeekOfFeb4

- Module4.1_Intro_to_Data_Structures_and_Algos/activities/Act3_Queues/4.md
> activity 4.1.3 Queues 4.md fixed

- LICENSE
- Module4_Labs/Lab6_Sudoku_Solver/Cards/6.md
- README.md
> Module4_Lab6_Sudoku_Solver: 6.md Fixed

- LICENSE
- Module4_Labs/Lab6_Sudoku_Solver/Cards/1.md
- README.md
> Module4_Lab6_Sudoku_Solver:1md Fixed

- Module4.1_Intro_to_Data_Structures_and_Algos/activities/Act3_Queues/2.md
> Activity 4.1.3 2.md fixed

- Module4.1_Intro_to_Data_Structures_and_Algos/activities/Act3_Queues/1.md
- Module4.1_Intro_to_Data_Structures_and_Algos/activities/Act3_Queues/11.md
Solved issue #159 (Also, I couldn't seem to drag and drop the Tempora cards properly to edit this; I'm sorry for the inconvenience)
> activity 4.1.3 Queues 1. md Fixed

- Module4_Labs/Lab1_BFS_Maze/Cards/1.md
- Module4_Labs/Lab1_BFS_Maze/Cards/11.md
- Module4_Labs/Lab1_BFS_Maze/Cards/31.md
- Module4_Labs/Lab1_BFS_Maze/Cards/32.md
Closes #271 
Closes #265 
2/12 Update
Split assigned cards into steps
> Closes #271, #265

- Module4_Labs/Lab6_Sudoku_Solver/Cards/8.md
Part 1 of #295
I am going to split the card into 2 cards. 
Closes Issues #295.
* Bullet point summary
@reviewer/Kevin
> Update 8.md #295

- Module4_Labs/Lab3_File_System/Cards/111.md
- Module4_Labs/Lab3_File_System/Cards/122.md
* Minor changes
@reviewer/Kevin
> Minor changes

- Module4.1_Intro_to_Data_Structures_and_Algos/activities/Act2_HashTables/1.md
- Module4.1_Intro_to_Data_Structures_and_Algos/activities/Act2_HashTables/2.md
- Module4_Labs/Lab6_Sudoku_Solver/Cards/4.md
- Module4_Labs/Lab6_Sudoku_Solver/Cards/411.md
- Module4_Labs/Lab6_Sudoku_Solver/Cards/71.md
Closes Issues #354  #333  #378 .
Please note that I am still working on fixing last issue that I was assigned. Will make a separate pull request for that.
* Example of findPossible() given
* fixed syntax problem in Sudoku lab solver 4.md + 411.md
* Sudoku solver Card - added note that copy.deepcopy() is a built in python function and told reader what they have to import
* Explained the data structures a HashTable are faster than in terms of indexing
* Explained basics of Big-O and specifically of O(1) in context of HashTables
@reviewer/Kevin
> [Lab 4.6, Activity 4.1.2] Sudoku Solver: Content; HashTables: Context

- Module4.1_Intro_to_Data_Structures_and_Algos/activities/Act2_HashTables/4.md
Fixed Card 4
Stage Labels: Difficulty = Hard, Issue = Context, Issue = Styling
Partially Closes Issues # 383.
- Introduced 1st paragraph better
- Stylized the paragraph after the image in a cleaner way
@sarahg500
> [Activity 4.1.2] HashTables Fixed Card 4

- Module4.1_Intro_to_Data_Structures_and_Algos/activities/Act2_HashTables/6.md
Fixed 6th card
Stage Label: Difficulty = Hard, Issue = Context, Issue = Styling
Closes Issues # 383.
- Split content of 1st paragraph into 2 paragraphs
@sarahg500
> [Activity 4.1.2] HashTables Fixed Card 6

- Module4.1_Intro_to_Data_Structures_and_Algos/activities/Act2_HashTables/3.md
Fixed Card 3 in Hash Table Activity
Stage Labels: Diff = Hard, Issue = Context, Issue = Styling
Partially Closes Issues # 383.
- Added concluding sentence
@sarahg500
> [Activity 4.1.2] HashTables Fixed Card 3

- Module4.1_Intro_to_Data_Structures_and_Algos/activities/Act4_Stacks/2.md
Fixed Cards 1 and 2
Stage: Difficulty = Hard, Issue = Context, Issue = Content
Closes Issues #371 .
- Made the bottom portion of the 1st Card straight to the point.
- Explained the reason why the result of applying the push() function in our stack class returns true for every element we put in for the stack.
@sarahg500
> [Activity 4.1.4] Stacks Fixed Cards 1 and 2 

- Module4.1_Intro_to_Data_Structures_and_Algos/activities/Act4_Stacks/1.md
Fixed Card 1
Stage Label: Difficulty = Hard, Issue = Context, Issue = Content
Closes Issues # 383.
- Made the bottom portion of the 1st card to be straight to the point
@sarahg500
> [Activity 4.1.4] Stacks Fixed Card 1

- Module4.2_Intermediate_Data_Structures/activities/Act1_LinkedLists/2.md
- Module4.2_Intermediate_Data_Structures/activities/Act1_LinkedLists/3.md
- Module4.2_Intermediate_Data_Structures/activities/Act1_LinkedLists/4.md
Closes Issues #88  #86  
* Add visuals and some explanation
> 4.2.1 Linked list 2/3/4.md

- Module4.2_Intermediate_Data_Structures/activities/Act2_Trees/InsertBefore3.md
Card on Recursion #397
**Don't forget a stage label and to set a reviewer and assignee to your reviewer. (please remove this line before starting your PR)**
Closes Issues #397 
Create a whole new card 
Formatting needs to be done. 
@sarahg500 /Kevin
> InsertBefore3

- Module4.2_Intermediate_Data_Structures/activities/Act2_Trees/1.md
Created a custom visual for the trees.
**Don't forget a stage label and to set a reviewer and assignee to your reviewer. (please remove this line before starting your PR)**
Closes Issues #399 
* Made a custom visual. Uploaded to Imgur 
@sarahg500
> Act2_Trees

- Module4_Labs/Lab3_File_System/Cards/21.md
- Module4_Labs/Lab3_File_System/Cards/211.md
- Module4_Labs/Lab3_File_System/Cards/22.md
- Module4_Labs/Lab3_File_System/Cards/221.md
Label: Difficulty = Hard, Issue = Content
Closes Issues #419 .
- Split info between Cards 21 and 211 evenly
- Told student that the necessary data structure to use is a dictionary in Card 22
- Explained purpose of storing and appending the node's information into our graph in Card 221
@sarahg500
> 4.3] file systems card 2 fixed

- Module4_Labs/Lab3_File_System/Cards/3.md
- Module4_Labs/Lab3_File_System/Cards/31.md
- Module4_Labs/Lab3_File_System/Cards/311.md
- Module4_Labs/Lab3_File_System/Cards/32.md
- Module4_Labs/Lab3_File_System/Cards/321.md
Labels: Difficulty = Hard, Issue = Context
Closes Issues #424 .
- Explained networkx functions in Card 3
- Added steps for Cards 31-32
@sarahg500
> 4.3] file systems card 3 edited

- Module4.2_Intermediate_Data_Structures/activities/Act3_Binary Heaps/README.md
* Bullet point summary
* I changed some headings and rearranged some things to make the readme fit the template in the link.
@reviewer/JasonL24
> joey updated readme for binary heap activity

- Module4.1_Intro_to_Data_Structures_and_Algos/activities/Act1_TimeAndSpaceComplexity/cards/1.md
- Module4.1_Intro_to_Data_Structures_and_Algos/activities/Act1_TimeAndSpaceComplexity/cards/2.md
- Module4.1_Intro_to_Data_Structures_and_Algos/activities/Act1_TimeAndSpaceComplexity/cards/3.md
- Module4.1_Intro_to_Data_Structures_and_Algos/activities/Act1_TimeAndSpaceComplexity/cards/4.md
- Module4.1_Intro_to_Data_Structures_and_Algos/activities/Act1_TimeAndSpaceComplexity/cards/5.md
- Module4.1_Intro_to_Data_Structures_and_Algos/activities/Act1_TimeAndSpaceComplexity/cards/6.md
- Module4.1_Intro_to_Data_Structures_and_Algos/activities/Act2_HashTables/cards/1.md
- Module4.1_Intro_to_Data_Structures_and_Algos/activities/Act2_HashTables/cards/2.md
- Module4.1_Intro_to_Data_Structures_and_Algos/activities/Act2_HashTables/cards/3.md
- Module4.1_Intro_to_Data_Structures_and_Algos/activities/Act2_HashTables/cards/4.md
- Module4.1_Intro_to_Data_Structures_and_Algos/activities/Act2_HashTables/cards/5.md
- Module4.1_Intro_to_Data_Structures_and_Algos/activities/Act2_HashTables/cards/6.md
- Module4.1_Intro_to_Data_Structures_and_Algos/activities/Act2_HashTables/cards/8.md
- Module4.1_Intro_to_Data_Structures_and_Algos/activities/Act3_Queues/cards/1.md
- Module4.1_Intro_to_Data_Structures_and_Algos/activities/Act3_Queues/cards/2.md
- Module4.1_Intro_to_Data_Structures_and_Algos/activities/Act3_Queues/cards/3.md
- Module4.1_Intro_to_Data_Structures_and_Algos/activities/Act3_Queues/cards/4.md
- Module4.1_Intro_to_Data_Structures_and_Algos/activities/Act4_Stacks/cards/1.md
- Module4.1_Intro_to_Data_Structures_and_Algos/activities/Act4_Stacks/cards/2.md
- Module4.1_Intro_to_Data_Structures_and_Algos/activities/Act4_Stacks/cards/3.md
- Module4.1_Intro_to_Data_Structures_and_Algos/activities/Act4_Stacks/cards/4.md
**Don't forget a stage label and to set a reviewer and assignee to your reviewer. (please remove this line before starting your PR)**
_Please make one new line for each issue, otherwise not all issues will be accounted for!_
Closes #xxx
Closes #xxx 
Closes #xxx
...
* Bullet point summary
@reviewer/kavuong
> Fixing Sarah-G

- Module_Twitter_API/activities/Act1_Intro to Twitter API/New/1.md
- Module_Twitter_API/activities/Act1_Intro to Twitter API/New/6.md
- Module_Twitter_API/activities/Act5_Sentiment Analysis with Twitter API/10.md
- Module_Twitter_API/activities/Act5_Sentiment Analysis with Twitter API/11.md
- Module_Twitter_API/activities/Act5_Sentiment Analysis with Twitter API/12.md
- Module_Twitter_API/activities/Act5_Sentiment Analysis with Twitter API/13.md
- Module_Twitter_API/activities/Act5_Sentiment Analysis with Twitter API/14.md
- Module_Twitter_API/activities/Act5_Sentiment Analysis with Twitter API/15.md
- Module_Twitter_API/activities/Act5_Sentiment Analysis with Twitter API/5.md
- Module_Twitter_API/activities/Act5_Sentiment Analysis with Twitter API/7.md
- Module_Twitter_API/activities/Act5_Sentiment Analysis with Twitter API/8.md
- Module_Twitter_API/activities/Act5_Sentiment Analysis with Twitter API/9.md
I resized the images for Activity 5 7.md-15.md, added example with halal guys(activity 5, 5.md), gave example of social science and twitter API (activity 1, 1.md), added explanation of main function (Activity 1, 6.md),
_Please make one new line for each issue, otherwise not all issues will be accounted for!_
Closes #940 
Closes #941 
...
* Bullet point summary
*resized images for activity 5 (7.md-15.md)
*Added example with halal Guys activity 5 (5.md)
*examples of social science and twitter API activity 1 (1.md)
*explanation of main function activity 1 (6.md)
@reviewer/kavuong
> First-Time

- Data-Structures-and-Algos-Topic/Module3-Search-and-Sorting-Algos/activities/Act2_Sorting/1.md
- Data-Structures-and-Algos-Topic/Module3-Search-and-Sorting-Algos/activities/Act2_Sorting/10.md
- Data-Structures-and-Algos-Topic/Module3-Search-and-Sorting-Algos/activities/Act2_Sorting/11.md
- Data-Structures-and-Algos-Topic/Module3-Search-and-Sorting-Algos/activities/Act2_Sorting/12.md
- Data-Structures-and-Algos-Topic/Module3-Search-and-Sorting-Algos/activities/Act2_Sorting/13.md
- Data-Structures-and-Algos-Topic/Module3-Search-and-Sorting-Algos/activities/Act2_Sorting/14.md
- Data-Structures-and-Algos-Topic/Module3-Search-and-Sorting-Algos/activities/Act2_Sorting/2.md
- Data-Structures-and-Algos-Topic/Module3-Search-and-Sorting-Algos/activities/Act2_Sorting/3.md
- Data-Structures-and-Algos-Topic/Module3-Search-and-Sorting-Algos/activities/Act2_Sorting/4-checkpoint.md
- Data-Structures-and-Algos-Topic/Module3-Search-and-Sorting-Algos/activities/Act2_Sorting/4.md
- Data-Structures-and-Algos-Topic/Module3-Search-and-Sorting-Algos/activities/Act2_Sorting/5.md
- Data-Structures-and-Algos-Topic/Module3-Search-and-Sorting-Algos/activities/Act2_Sorting/6.md
- Data-Structures-and-Algos-Topic/Module3-Search-and-Sorting-Algos/activities/Act2_Sorting/7.md
- Data-Structures-and-Algos-Topic/Module3-Search-and-Sorting-Algos/activities/Act2_Sorting/8.md
- Data-Structures-and-Algos-Topic/Module3-Search-and-Sorting-Algos/activities/Act2_Sorting/9.md
Final part of Module 2 edits. Edited Activity 2 in Module 3 (meant for Module 2) called Sorting.
_Please make one new line for each issue, otherwise not all issues will be accounted for!_
Closes #949 
...
*Bullet Point Summary
- Final part of edits for Module 2 content
- Edited all of Activity 2 called "Sorting" in Module 3 (but meant for Module 2)
@reviewer/kavuong
> Module 2 sorting algs activity

- Module_Twitter_API/labs/Week 1/Visualizing Tweets - Celebrities/0.md
- Module_Twitter_API/labs/Week 1/Visualizing Tweets - Celebrities/labREADME.md
* README the one Bryan mentioned
* add definition of tokens in 0.md
@ojgao
> labREADME.md
